version: '3'
services:
  backend:
    build: ./Back-End
    ports:
      - "5001:5000"
  
  frontend:
    build: ./Front-End
    ports:
      - "8080:5000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
